[package]
name = "mechanix-greeter"
description = "Greeter (login or display manager) component for the Mechanix shell"
version = "0.1.0"
edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true
categories.workspace = true
keywords.workspace = true

[dependencies]
anyhow = "1.0.71"
serde = { version = "1.0.163", features = ["derive"] }
serde_yaml = "0.9.21"
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
greetd_ipc = { version = "0.9.0", features = ["tokio-codec"] }
tokio = { version = "1.33", features = ["full"] }
mctk_core = { workspace = true }
mctk_smithay = { workspace = true }
mctk_macros = { workspace = true }
smithay-client-toolkit = { workspace = true }
futures = { workspace = true }
image = { workspace = true }
mechanix_system_dbus_client = { workspace = true }
chrono = { workspace = true }
mechanix_status_bar_components = { workspace = true }
const_format = { workspace = true }
dirs = { workspace = true }

[package.metadata.deb]
assets = [
    # binary
    [
        "../target/release/mechanix-greeter",
        "/usr/bin/mechanix-greeter",
        "755",
    ],

    # service
    [
        "settings.yml.example",
        "/etc/mechanix/shell/greeter/settings.yml",
        "644",
    ],

    # user-settings
    [
        "users.yml.example",
        "/etc/mechanix/shell/greeter/users.yml",
        "644",
    ],

    # assets
    [
        "src/assets/**/*",
        "/usr/share/mechanix/shell/greeter/assets",
        "644",
    ],
]
