[package]
name = "mechanix_store_server"
description = "Zbus interface for Mechanix System services"
version = "0.1.0"
edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true
categories.workspace = true
keywords.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
sled = "0.34.7"
anyhow.workspace = true
serde.workspace = true
tokio.workspace = true
zbus.workspace = true
dirs = "5.0.1"

[package.metadata.deb]
name = "mechanix_store_server"
depends = "$auto"
assets = [
    # binary
    [
        "../../target/release/mechanix_store_server",
        "/usr/bin/",
        "755",
    ],
]